export const migration = {
  version: 21,
  name: "responses_unknown_protocol",
  sql: [
    "CREATE TABLE usage_buckets_v21 (",
    "  utc_hour_ms INTEGER NOT NULL,",
    "  account_id TEXT NOT NULL,",
    "  protocol TEXT NOT NULL CHECK (protocol IN (",
    "    'openai_chat', 'openai_responses_unknown', 'openai_responses_native',",
    "    'openai_responses_bridge', 'anthropic', 'ollama'",
    "  )),",
    "  resolved_model TEXT NOT NULL,",
    "  outcome TEXT NOT NULL CHECK (outcome IN (",
    "    'success', 'client_error', 'authentication_error', 'overloaded',",
    "    'upstream_error', 'timeout', 'aborted', 'internal_error'",
    "  )),",
    "  request_count INTEGER NOT NULL,",
    "  error_count INTEGER NOT NULL,",
    "  input_tokens INTEGER NOT NULL,",
    "  output_tokens INTEGER NOT NULL,",
    "  cache_tokens INTEGER NOT NULL,",
    "  latency_sum_ms REAL NOT NULL,",
    "  latency_max_ms REAL NOT NULL,",
    "  PRIMARY KEY(utc_hour_ms, account_id, protocol, resolved_model, outcome)",
    ");",
    "INSERT INTO usage_buckets_v21 SELECT * FROM usage_buckets;",
    "DROP TABLE usage_buckets;",
    "ALTER TABLE usage_buckets_v21 RENAME TO usage_buckets;",
    "CREATE INDEX usage_buckets_utc_hour_ms ON usage_buckets(utc_hour_ms);",
  ].join("\n"),
} as const;
