export const migration = {
  version: 41,
  name: "responses_continuation_ownership",
  sql: [
    "CREATE TABLE responses_continuation_state (",
    "  singleton_id INTEGER PRIMARY KEY CHECK (singleton_id = 1),",
    "  revision INTEGER NOT NULL,",
    "  next_receipt_seq INTEGER NOT NULL,",
    "  next_checkpoint_seq INTEGER NOT NULL,",
    "  updated_at_ms INTEGER NOT NULL",
    ");",
    "CREATE TABLE response_route_receipts (",
    "  account_id TEXT NOT NULL,",
    "  response_id TEXT NOT NULL,",
    "  model_id TEXT NOT NULL,",
    "  upstream_origin TEXT NOT NULL,",
    "  owner TEXT NOT NULL CHECK (owner IN ('native', 'converted')),",
    "  upstream_protocol TEXT NOT NULL CHECK (upstream_protocol IN ('responses', 'chat', 'messages')),",
    "  conversion_version TEXT,",
    "  checkpoint_state TEXT NOT NULL CHECK (checkpoint_state IN ('route_only', 'partial', 'complete', 'expired')),",
    "  insertion_seq INTEGER NOT NULL UNIQUE,",
    "  created_at_ms INTEGER NOT NULL,",
    "  expires_at_ms INTEGER NOT NULL,",
    "  PRIMARY KEY(account_id, response_id),",
    "  CHECK ((owner = 'native' AND upstream_protocol = 'responses' AND conversion_version IS NULL)",
    "    OR (owner = 'converted' AND upstream_protocol IN ('chat', 'messages') AND conversion_version IS NOT NULL))",
    ");",
    "CREATE TABLE response_scoped_checkpoints (",
    "  account_id TEXT NOT NULL,",
    "  response_id TEXT NOT NULL,",
    "  insertion_seq INTEGER NOT NULL UNIQUE,",
    "  created_at_ms INTEGER NOT NULL,",
    "  expires_at_ms INTEGER NOT NULL,",
    "  PRIMARY KEY(account_id, response_id),",
    "  FOREIGN KEY(account_id, response_id) REFERENCES response_route_receipts(account_id, response_id) ON DELETE CASCADE",
    ");",
    "CREATE TABLE response_scoped_calls (",
    "  account_id TEXT NOT NULL,",
    "  response_id TEXT NOT NULL,",
    "  ordinal INTEGER NOT NULL,",
    "  call_id TEXT NOT NULL,",
    "  kind TEXT NOT NULL CHECK (kind IN ('function_call', 'custom_tool_call', 'tool_search_call')),",
    "  item_json TEXT NOT NULL,",
    "  PRIMARY KEY(account_id, response_id, ordinal),",
    "  FOREIGN KEY(account_id, response_id) REFERENCES response_scoped_checkpoints(account_id, response_id) ON DELETE CASCADE",
    ");",
    "CREATE TABLE response_receipt_uncertainty (",
    "  singleton_id INTEGER PRIMARY KEY CHECK (singleton_id = 1),",
    "  uncertain_since_ms INTEGER NOT NULL",
    ");",
    "CREATE INDEX response_route_receipts_response_id ON response_route_receipts(response_id);",
    "CREATE INDEX response_route_receipts_expiry ON response_route_receipts(expires_at_ms, checkpoint_state);",
    "CREATE INDEX response_scoped_checkpoints_expiry ON response_scoped_checkpoints(expires_at_ms);",
    "CREATE INDEX response_scoped_calls_lookup ON response_scoped_calls(account_id, response_id, call_id);",
    "INSERT INTO responses_continuation_state",
    "  (singleton_id, revision, next_receipt_seq, next_checkpoint_seq, updated_at_ms)",
    "SELECT 1, revision, 1, 1, updated_at_ms",
    "FROM responses_history_state WHERE singleton_id = 1;",
  ].join("\n"),
} as const;
