export const migration = {
  version: 42,
  name: "responses_reasoning_carriers",
  sql: [
    "ALTER TABLE response_scoped_checkpoints ADD COLUMN replay_format_version INTEGER NOT NULL DEFAULT 1 CHECK (replay_format_version IN (1, 2));",
    "ALTER TABLE response_scoped_checkpoints ADD COLUMN replay_item_count INTEGER NOT NULL DEFAULT 0 CHECK (replay_item_count >= 0);",
    "ALTER TABLE response_scoped_checkpoints ADD COLUMN replay_bytes INTEGER NOT NULL DEFAULT 0 CHECK (replay_bytes >= 0);",
    "CREATE TABLE response_scoped_replay_items (",
    "  account_id TEXT NOT NULL,",
    "  response_id TEXT NOT NULL,",
    "  group_ordinal INTEGER NOT NULL CHECK (group_ordinal >= 0),",
    "  item_ordinal INTEGER NOT NULL CHECK (item_ordinal >= 0),",
    "  item_kind TEXT NOT NULL CHECK (item_kind IN ('reasoning', 'function_call', 'custom_tool_call', 'tool_search_call')),",
    "  call_id TEXT,",
    "  item_json TEXT NOT NULL,",
    "  item_bytes INTEGER NOT NULL CHECK (item_bytes > 0 AND item_bytes = length(CAST(item_json AS BLOB))),",
    "  PRIMARY KEY(account_id, response_id, group_ordinal, item_ordinal),",
    "  FOREIGN KEY(account_id, response_id) REFERENCES response_scoped_checkpoints(account_id, response_id) ON DELETE CASCADE,",
    "  CHECK ((item_kind = 'reasoning' AND call_id IS NULL) OR (item_kind <> 'reasoning' AND call_id IS NOT NULL AND length(call_id) > 0))",
    ");",
    "CREATE INDEX response_scoped_replay_calls_lookup ON response_scoped_replay_items(account_id, response_id, call_id) WHERE call_id IS NOT NULL;",
    "CREATE TABLE reasoning_carriers (",
    "  carrier_id TEXT PRIMARY KEY,",
    "  token TEXT NOT NULL UNIQUE,",
    "  account_id TEXT NOT NULL,",
    "  model_id TEXT NOT NULL,",
    "  upstream_origin TEXT NOT NULL,",
    "  source_protocol TEXT NOT NULL CHECK (source_protocol IN ('chat', 'messages', 'responses')),",
    "  wire_protocol TEXT NOT NULL CHECK (wire_protocol IN ('chat', 'messages', 'responses')),",
    "  conversion_version TEXT NOT NULL,",
    "  source_kind TEXT NOT NULL CHECK (source_kind IN ('chat_state', 'messages_block', 'responses_item')),",
    "  state TEXT NOT NULL CHECK (state IN ('partial', 'complete')),",
    "  response_id TEXT,",
    "  payload_json TEXT NOT NULL,",
    "  projection_json TEXT NOT NULL,",
    "  stored_bytes INTEGER NOT NULL CHECK (stored_bytes > 0 AND stored_bytes = length(CAST(payload_json AS BLOB)) + length(CAST(projection_json AS BLOB))),",
    "  insertion_seq INTEGER NOT NULL UNIQUE,",
    "  created_at_ms INTEGER NOT NULL,",
    "  expires_at_ms INTEGER NOT NULL",
    ");",
    "CREATE INDEX reasoning_carriers_binding ON reasoning_carriers(account_id, token, state);",
    "CREATE INDEX reasoning_carriers_expiry ON reasoning_carriers(expires_at_ms, state);",
    "INSERT INTO response_scoped_replay_items (account_id, response_id, group_ordinal, item_ordinal, item_kind, call_id, item_json, item_bytes)",
    "SELECT account_id, response_id, 0, ordinal, kind, call_id, item_json, length(CAST(item_json AS BLOB)) FROM response_scoped_calls;",
    "UPDATE response_scoped_checkpoints SET",
    "  replay_item_count = (SELECT COUNT(*) FROM response_scoped_replay_items AS item WHERE item.account_id = response_scoped_checkpoints.account_id AND item.response_id = response_scoped_checkpoints.response_id),",
    "  replay_bytes = COALESCE((SELECT SUM(item_bytes) FROM response_scoped_replay_items AS item WHERE item.account_id = response_scoped_checkpoints.account_id AND item.response_id = response_scoped_checkpoints.response_id), 0);",
  ].join("\n"),
} as const;
